version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: user_management_db
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_VERSION: 18
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d user_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: user_management_postgres_data