services:
  postgres-db:
    image: postgres:15-alpine
    container_name: user_management_db
    environment:
      # These must match your DATABASE_USERNAME and DATABASE_PASSWORD
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      # This must match the DB name in your DATABASE_URL
      POSTGRES_DB: user_management
    ports:
      - "3307:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d user_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: